# Generated by Django 3.0.4 on 2020-04-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=5000)),
                ('author', models.CharField(blank=True, max_length=5000)),
                ('title', models.CharField(blank=True, max_length=5000)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('url', models.CharField(blank=True, max_length=5000)),
                ('image', models.CharField(blank=True, max_length=5000)),
                ('published', models.CharField(blank=True, max_length=5000)),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('totalResults', models.CharField(blank=True, max_length=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
