# Generated by Django 3.0.4 on 2020-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_saved_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_articles',
            name='preference',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
